/* 1 - RELATÓRIO GERAL DE TODOS OS CLIENTES*/

SELECT C.NOME, C.SEXO, C.EMAIL, C.CPF, T.TIPO, T.NUMERO, E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO 
FROM CLIENTE C 
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE;

/* 2 - RELATÓRIO GERAL DE HOMENS*/

SELECT C.NOME, C.SEXO, C.EMAIL, C.CPF, T.TIPO, T.NUMERO, E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO 
FROM CLIENTE C 
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
WHERE SEXO = 'M';

/* 3 - RELATÓRIO GERAL DE MULHERES*/

SELECT C.NOME, C.SEXO, C.EMAIL, C.CPF, T.TIPO, T.NUMERO, E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO 
FROM CLIENTE C 
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
WHERE SEXO = 'F';

/* 4 - QUANTIDADE DE HOMENS E MULHERES*/

SELECT C.SEXO, COUNT(*) AS QTD 
FROM CLIENTE C
GROUP BY C.SEXO;

/* 5 - NOME, EMAIL, TEL CELULAR DOS CLIENTES QUE MORAM NO RIO DE JANEIRO*/

SELECT C.NOME, C.EMAIL, T.NUMERO AS CELULAR, E.ESTADO 
FROM CLIENTE C
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
WHERE E.ESTADO = 'RJ' 
AND T.TIPO = 'CELULAR';

/* 6 - OUTRA FORMA DE UTILIZAR O WHERE. A CLÁUSULA IN PERMITE DEFINIR UM CONJUNTO DE VALORES PARA UMA SELEÇÃO.*/

SELECT * FROM CLIENTE 
WHERE IDCLIENTE IN ( 1, 2, 3);

/* 7 - NOME, EMAIL, CELULAR DAS CLIENTES QUE MORAM EM SP*/

SELECT C.NOME, C.EMAIL, T.NUMERO AS CELULAR, E.ESTADO 
FROM CLIENTE C
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E 
ON C.IDCLIENTE = E.ID_CLIENTE
WHERE C.SEXO = 'F' AND E.ESTADO = 'SP';

