/*SQL BÁSICO DE UM BANCO DE DADOS ORACLE*/

/*1 - CRIANDO TABELAS E DEFININDO CONSTRAINTS*/ 

/*SETORES*/

CREATE TABLE T_SETORES (

	SET_ID NUMBER,
	SET_NOME VARCHAR2(40),
	CONSTRAINT UNQ_SETORES_NOME UNIQUE (SET_NOME),
	CONSTRAINT PK_SETORES_ID PRIMARY KEY (SET_ID)

);

/*PRODUTOS*/

CREATE TABLE T_PRODUTOS (

	PRO_ID NUMBER,
	PRO_NOME VARCHAR2(30) NOT NULL, 
	PRO_PRECO NUMBER(8,2) NOT NULL,
	PRO_DT_VALIDADE DATE,
	PRO_ORIGEM VARCHAR2(6),
	PRO_ID_SETOR NUMBER NOT NULL,

	CONSTRAINT PK_PRODUTOS_ID PRIMARY KEY (PRO_ID),
	CONSTRAINT CHK_PRODUTOS_ORIGEM CHECK(PRO_ORIGEM IN ('BRAZIL', 'AFRICA', 'CHINA')),
	CONSTRAINT UNQ_PRODUTOS_NOME UNIQUE(PRO_NOME),
	CONSTRAINT FK_PRODUTOS_SETORES FOREIGN KEY (PRO_ID_SETOR) REFERENCES T_SETORES(SET_ID)
);

/*DEFININDO SEQUENCES E TRIGGERS PARA GERENCIAR AS PKs*/

/*SETORES*/

CREATE SEQUENCE SET_SEQ_ID
START WITH 1 
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER SET_TRIG_ID
BEFORE INSERT
ON "T_SETORES"
FOR EACH ROW 
BEGIN
SELECT SET_SEQ_ID.nextval INTO:NEW.SET_ID 
FROM DUAL;
END;

/*PRODUTOS*/

CREATE SEQUENCE PRO_SEQ_ID
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER PRO_TRIG_ID
BEFORE INSERT
ON "T_PRODUTOS"
FOR EACH ROW
BEGIN
SELECT PRO_SEQ_ID.nextval INTO:NEW.PRO_ID
FROM DUAL;
END;

/*POVOAMENTE INICIAL*/

/*SETORES*/

INSERT INTO T_SETORES (SET_NOME) VALUES('MERCEARIA');
INSERT INTO T_SETORES (SET_NOME) VALUES('FRIOS');
INSERT INTO T_SETORES (SET_NOME) VALUES('BAZAR');
INSERT INTO T_SETORES (SET_NOME) VALUES('ADEGA');
INSERT INTO T_SETORES (SET_NOME) VALUES('HORTIFRUTI'); 

/*PRODUTOS*/

/*MERCEARIA*/

INSERT INTO T_PRODUTOS (PRO_ORIGEM, PRO_NOME, PRO_PRECO, PRO_DT_VALIDADE, PRO_ID_SETOR) VALUES ('BRAZIL', 'FEIJAO 5KG', 12.90, TO_DATE('2023-06-29', 'YYYY-MM-DD'), 1);
INSERT INTO T_PRODUTOS (PRO_ORIGEM, PRO_NOME, PRO_PRECO, PRO_DT_VALIDADE, PRO_ID_SETOR) VALUES ('BRAZIL', 'ARROZ 5KG', 62.90, TO_DATE('2023-09-29', 'YYYY-MM-DD'), 1);
INSERT INTO T_PRODUTOS (PRO_ORIGEM, PRO_NOME, PRO_PRECO, PRO_DT_VALIDADE, PRO_ID_SETOR) VALUES ('CHINA', 'SAL 1KG', 9.90, TO_DATE('2024-05-29', 'YYYY-MM-DD'), 1);
INSERT INTO T_PRODUTOS (PRO_ORIGEM, PRO_NOME, PRO_PRECO, PRO_DT_VALIDADE, PRO_ID_SETOR) VALUES ('CHINA', 'SAL 2KG', 15.90, TO_DATE('2024-05-29', 'YYYY-MM-DD'), 1);
INSERT INTO T_PRODUTOS (PRO_ORIGEM, PRO_NOME, PRO_PRECO, PRO_DT_VALIDADE, PRO_ID_SETOR) VALUES ('CHINA', 'SAL 5KG', 40.90, TO_DATE('2024-05-29', 'YYYY-MM-DD'), 1);
INSERT INTO T_PRODUTOS (PRO_ORIGEM, PRO_NOME, PRO_PRECO, PRO_DT_VALIDADE, PRO_ID_SETOR) VALUES ('AFRICA', 'AÇUCAR 2KG', 39.90, TO_DATE('2024-05-29', 'YYYY-MM-DD'), 1);

/*FRIOS*/

INSERT INTO T_PRODUTOS (PRO_ORIGEM, PRO_NOME, PRO_PRECO, PRO_DT_VALIDADE, PRO_ID_SETOR) VALUES ('BRAZIL', 'LEITE 900ML', 8.90, TO_DATE('2023-03-27', 'YYYY-MM-DD'), 2);
INSERT INTO T_PRODUTOS (PRO_ORIGEM, PRO_NOME, PRO_PRECO, PRO_DT_VALIDADE, PRO_ID_SETOR) VALUES ('BRAZIL', 'IOGURTE 1L', 15.90, TO_DATE('2023-06-29', 'YYYY-MM-DD'), 2);
INSERT INTO T_PRODUTOS (PRO_ORIGEM, PRO_NOME, PRO_PRECO, PRO_DT_VALIDADE, PRO_ID_SETOR) VALUES ('BRAZIL', 'MANTEIGA 500G', 11.90, TO_DATE('2023-05-29', 'YYYY-MM-DD'), 2);
INSERT INTO T_PRODUTOS (PRO_ORIGEM, PRO_NOME, PRO_PRECO, PRO_DT_VALIDADE, PRO_ID_SETOR) VALUES ('CHINA', 'PATÊ DE FRANGO 200G', 14.90, TO_DATE('2023-04-02', 'YYYY-MM-DD'), 2);
INSERT INTO T_PRODUTOS (PRO_ORIGEM, PRO_NOME, PRO_PRECO, PRO_DT_VALIDADE, PRO_ID_SETOR) VALUES ('AFRICA', 'REQUEIJAO 1KG', 30.90, TO_DATE('2023-04-07', 'YYYY-MM-DD'), 2);
INSERT INTO T_PRODUTOS (PRO_ORIGEM, PRO_NOME, PRO_PRECO, PRO_DT_VALIDADE, PRO_ID_SETOR) VALUES ('AFRICA', 'CHEDDAR 1KG', 42.90, TO_DATE('2023-03-29', 'YYYY-MM-DD'), 2);

/*BAZAR*/

INSERT INTO T_PRODUTOS (PRO_ORIGEM, PRO_NOME, PRO_PRECO, PRO_ID_SETOR) VALUES ('BRAZIL', 'CADEIRA', 92.90, 3);
INSERT INTO T_PRODUTOS (PRO_ORIGEM, PRO_NOME, PRO_PRECO, PRO_ID_SETOR) VALUES ('BRAZIL', 'MESA', 245.90, 3);
INSERT INTO T_PRODUTOS (PRO_ORIGEM, PRO_NOME, PRO_PRECO, PRO_ID_SETOR) VALUES ('CHINA', 'MOLDURA' , 19.90, 3);
INSERT INTO T_PRODUTOS (PRO_ORIGEM, PRO_NOME, PRO_PRECO, PRO_ID_SETOR) VALUES ('CHINA', 'GUARDA-SOL', 81.90, 3);
INSERT INTO T_PRODUTOS (PRO_ORIGEM, PRO_NOME, PRO_PRECO, PRO_ID_SETOR) VALUES ('AFRICA', 'ALMOFADA', 59.90, 3);
INSERT INTO T_PRODUTOS (PRO_ORIGEM, PRO_NOME, PRO_PRECO, PRO_ID_SETOR) VALUES ('AFRICA', 'DOBRADIÇA', 9.90, 3);

/*ADEGA*/

INSERT INTO T_PRODUTOS (PRO_ORIGEM, PRO_NOME, PRO_PRECO, PRO_DT_VALIDADE, PRO_ID_SETOR) VALUES ('BRAZIL', 'VINHO BRANCO A2 SUAVE', 62.90, TO_DATE('2029-06-29', 'YYYY-MM-DD'), 4);
INSERT INTO T_PRODUTOS (PRO_ORIGEM, PRO_NOME, PRO_PRECO, PRO_DT_VALIDADE, PRO_ID_SETOR) VALUES ('BRAZIL', 'VINHO TINTO SECO', 92.90, TO_DATE('2030-09-29', 'YYYY-MM-DD'), 4);
INSERT INTO T_PRODUTOS (PRO_ORIGEM, PRO_NOME, PRO_PRECO, PRO_DT_VALIDADE, PRO_ID_SETOR) VALUES ('CHINA', 'VINHO ROSE A2 BRUT', 150.90, TO_DATE('2027-05-29', 'YYYY-MM-DD'), 4);
INSERT INTO T_PRODUTOS (PRO_ORIGEM, PRO_NOME, PRO_PRECO, PRO_DT_VALIDADE, PRO_ID_SETOR) VALUES ('AFRICA', 'VINHO TINTO A3 SECO', 62.90, TO_DATE('2029-06-29', 'YYYY-MM-DD'), 4);
INSERT INTO T_PRODUTOS (PRO_ORIGEM, PRO_NOME, PRO_PRECO, PRO_DT_VALIDADE, PRO_ID_SETOR) VALUES ('AFRICA', 'VINHO TINTO B1 BRUT', 92.90, TO_DATE('2030-09-29', 'YYYY-MM-DD'), 4);
INSERT INTO T_PRODUTOS (PRO_ORIGEM, PRO_NOME, PRO_PRECO, PRO_DT_VALIDADE, PRO_ID_SETOR) VALUES ('AFRICA', 'VINHO BRANCO B9 SUAVE', 400.90, TO_DATE('2031-05-29', 'YYYY-MM-DD'), 4);

/*HORTIFRUTI*/

INSERT INTO T_PRODUTOS (PRO_ORIGEM, PRO_NOME, PRO_PRECO, PRO_DT_VALIDADE, PRO_ID_SETOR) VALUES ('BRAZIL', 'BANDEJA 16 OVOS', 17.90, TO_DATE('2023-05-26', 'YYYY-MM-DD'), 5);
INSERT INTO T_PRODUTOS (PRO_ORIGEM, PRO_NOME, PRO_PRECO, PRO_DT_VALIDADE, PRO_ID_SETOR) VALUES ('BRAZIL', 'ABABAXI UND', 12.90, TO_DATE('2023-01-09', 'YYYY-MM-DD'), 5);
INSERT INTO T_PRODUTOS (PRO_ORIGEM, PRO_NOME, PRO_PRECO, PRO_DT_VALIDADE, PRO_ID_SETOR) VALUES ('CHINA', 'MELANCIA UND.', 30.90, TO_DATE('2023-02-19', 'YYYY-MM-DD'), 5);
INSERT INTO T_PRODUTOS (PRO_ORIGEM, PRO_NOME, PRO_PRECO, PRO_DT_VALIDADE, PRO_ID_SETOR) VALUES ('CHINA', 'MELAO S/ SEMENTE UND.', 47.90, TO_DATE('2023-05-26', 'YYYY-MM-DD'), 5);
INSERT INTO T_PRODUTOS (PRO_ORIGEM, PRO_NOME, PRO_PRECO, PRO_DT_VALIDADE, PRO_ID_SETOR) VALUES ('CHINA', 'ALFACE UND.', 9.90, TO_DATE('2023-01-09', 'YYYY-MM-DD'), 5);
INSERT INTO T_PRODUTOS (PRO_ORIGEM, PRO_NOME, PRO_PRECO, PRO_DT_VALIDADE, PRO_ID_SETOR) VALUES ('CHINA', 'CEBOLA UND.', 30.90, TO_DATE('2023-02-19', 'YYYY-MM-DD'), 5);

