CREATE DATABASE PROJETO;

USE PROJETO;

CREATE TABLE CURSOS(
	IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	HORAS INT(3) NOT NULL,
	VALOR FLOAT(10,2) NOT NULL
);

CREATE TABLE ALUNOS(
	IDALUNO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM ('F', 'M') NOT NULL,
	EMAIL VARCHAR (30)NOT NULL,
	IDADE INT NOT NULL
);

CREATE TABLE R_MATRICULA (
	IDMATRICULA INT PRIMARY KEY AUTO_INCREMENT,
	DT_MATRICULA DATE,
	ID_ALUNO INT NOT NULL, /* CADA ALUNO PODE SE MATRICULAR EM MAIS DE UM CURSO, ENTÃO NÃO É UNIQUE.*/
	ID_CURSO INT NOT NULL, /* CADA CURSO PODE TER MATRICULADO MAIS DE UM ALUNO, ENTÃO NÃO É UNIQUE.*/	
	FOREIGN KEY (ID_ALUNO) REFERENCES ALUNOS(IDALUNO),
	FOREIGN KEY (ID_CURSO) REFERENCES CURSOS(IDCURSO)
);