
/* PROCEDURE PARA LISTAR OS CURSOS EM QUE UM ALUNO X ESTÁ MATRICULADO */

DELIMITER $

CREATE PROCEDURE LISTAR_CURSOS(P_IDALUNO INT)
BEGIN
SELECT A.NOME,
 	A.SEXO,
  	A.EMAIL,
	R.DT_MATRICULA,
    C.NOME AS CURSO
FROM ALUNOS A 
INNER JOIN R_MATRICULA R
ON A.IDALUNO = R.ID_ALUNO
INNER JOIN CURSOS C
ON C.IDCURSO = R.ID_CURSO
WHERE A.IDALUNO = P_IDALUNO;
END
$

DELIMITER ;

/* PROCEDURE PARA LISTAR OS ALUNOS MATRICULADOS EM UM CURSO X */

DELIMITER $

CREATE PROCEDURE LISTAR_ALUNOS(P_IDCURSO INT)
BEGIN
SELECT A.NOME,
 	A.SEXO,
  	A.EMAIL,
	R.DT_MATRICULA,
    C.NOME AS CURSO
FROM ALUNOS A 
INNER JOIN R_MATRICULA R
ON A.IDALUNO = R.ID_ALUNO
INNER JOIN CURSOS C
ON C.IDCURSO = R.ID_CURSO
WHERE C.IDCURSO = P_IDCURSO;
END
$

DELIMITER ;

/* PROCEDURE PARA MOSTRAR QUANTOS ALUNOS ESTÃO MATRICULADOS EM CADA CURSO */

DELIMITER $

CREATE PROCEDURE ALUNOS_POR_CURSO()
BEGIN
SELECT C.NOME AS CURSO, COUNT(R.IDMATRICULA) AS 'QTD DE ALUNOS' 
FROM CURSOS C
INNER JOIN R_MATRICULA R
ON C.IDCURSO = R.ID_CURSO /* CONSIDERAR APENAS OS CURSOS QUE POSSUEM MATRÍCULAS */
GROUP BY C.NOME
ORDER BY 2 DESC ; /* ORDER BY 2 = COUNT(R.IDMATRICULA), DESC = DESCENDENTE*/
END
$

DELIMITER ;
