/* INSERTS PARA TESTE */

/* SERVICOS */

INSERT INTO SERVICO VALUES (NULL, 'TROCA PNEU', '200');
INSERT INTO SERVICO VALUES (NULL, 'TROCA ÓLEO', '250');
INSERT INTO SERVICO VALUES (NULL, 'TROCA PARA-BRISA', '300');
INSERT INTO SERVICO VALUES (NULL, 'PINTURA', '1000');
INSERT INTO SERVICO VALUES (NULL, 'LAVAGEM EXTERNA', '50');

/* CORES */

INSERT INTO COR VALUES (NULL, 'ROSA', '180');
INSERT INTO COR VALUES (NULL, 'VERMELHO', '240');
INSERT INTO COR VALUES (NULL, 'PRETO', '320');
INSERT INTO COR VALUES (NULL, 'PRATA', '300');
INSERT INTO COR VALUES (NULL, 'BRANCO', '200');

/* MARCA */

INSERT INTO MARCA VALUES (NULL, 'FIAT', 20.90);
INSERT INTO MARCA VALUES (NULL, 'CHEVROLET', 45.90);
INSERT INTO MARCA VALUES (NULL, 'FORD', 50.90);
INSERT INTO MARCA VALUES (NULL, 'NISSAN', 100.90);
INSERT INTO MARCA VALUES (NULL, 'VOLKSWAGEN', 30.90);

/* CLIENTE */

INSERT INTO CLIENTE VALUES (NULL, 'CARLOS', 'M');
INSERT INTO CLIENTE VALUES (NULL, 'BEATRIZ', 'F');
INSERT INTO CLIENTE VALUES (NULL, 'KARMEN', 'F');
INSERT INTO CLIENTE VALUES (NULL, 'ANA', 'F');
INSERT INTO CLIENTE VALUES (NULL, 'MIGUEL', 'M');

/* TELEFONE */

INSERT INTO TELEFONE VALUES (NULL, 'RES', '4539976321', 1);
INSERT INTO TELEFONE VALUES (NULL, 'CEL', '45933300321', 1);
INSERT INTO TELEFONE VALUES (NULL, 'RES', '4539800021', 3);
INSERT INTO TELEFONE VALUES (NULL, 'CEL', '40900976321', 4);
INSERT INTO TELEFONE VALUES (NULL, 'CEL', '45939776321', 5);


/* CARRO */

INSERT INTO CARRO VALUES (NULL, 'FORD KA', 'A67GCF2', 1, 3);
INSERT INTO CARRO VALUES (NULL, 'FORD FOCUS', '2B7GCF2', 2, 3);
INSERT INTO CARRO VALUES (NULL, 'NISSAN KICKS', 'A67TTF2', 3, 4);
INSERT INTO CARRO VALUES (NULL, 'FIAT MOBI', 'B67GHH8', 4, 1);
INSERT INTO CARRO VALUES (NULL, 'VOLKSWAGEN FUSCA', 'C67GCF2', 5, 5);

/* ASS CARRO COR */

INSERT INTO ASS_CARRO_COR VALUES (4,3);	
INSERT INTO ASS_CARRO_COR VALUES (4,2);	
INSERT INTO ASS_CARRO_COR VALUES (4,1);	
INSERT INTO ASS_CARRO_COR VALUES (1,3);	
INSERT INTO ASS_CARRO_COR VALUES (2,2);	
INSERT INTO ASS_CARRO_COR VALUES (3,5);	
INSERT INTO ASS_CARRO_COR VALUES (3,2);	
INSERT INTO ASS_CARRO_COR VALUES (5,1);	

/* ATENDIMENTO */

INSERT INTO ATENDIMENTO VALUES (NULL, 1, 1, '2021:08:22', 'CARRO CHEGOU À OFICINA JÁ COM AMASSADOS');
INSERT INTO ATENDIMENTO VALUES (NULL, 2, 2, '2022:01:27', 'CARRO CHEGOU À OFICINA COM RISCOS NA LATERAL ESQUERDA');
INSERT INTO ATENDIMENTO VALUES (NULL, 3, 3, '2022:02:18', 'CARRO CHEGOU À OFICINA SEM O PARA-BRISA ESQUERDO');
INSERT INTO ATENDIMENTO VALUES (NULL, 4, 4, '2022:02:12', 'CARRO CHEGOU À OFICINA JÁ COM AMASSADOS');
INSERT INTO ATENDIMENTO VALUES (NULL, 5, 5, '2022:07:22', 'CARRO CHEGOU À OFICINA COM OS DOIS PNEUS DA FRENTE FURADOS');

/* ASS ATENDIMENTO SERVICO */

INSERT INTO ASS_SERVICO_ATENDIMENTO VALUES (1,2);
INSERT INTO ASS_SERVICO_ATENDIMENTO VALUES (3,2);
INSERT INTO ASS_SERVICO_ATENDIMENTO VALUES (2,2);
INSERT INTO ASS_SERVICO_ATENDIMENTO VALUES (1,1);
INSERT INTO ASS_SERVICO_ATENDIMENTO VALUES (5,3);
INSERT INTO ASS_SERVICO_ATENDIMENTO VALUES (1,3);
INSERT INTO ASS_SERVICO_ATENDIMENTO VALUES (2,3);
INSERT INTO ASS_SERVICO_ATENDIMENTO VALUES (4,4);
INSERT INTO ASS_SERVICO_ATENDIMENTO VALUES (3,4);
INSERT INTO ASS_SERVICO_ATENDIMENTO VALUES (1,5);
INSERT INTO ASS_SERVICO_ATENDIMENTO VALUES (2,5);