CREATE DATABASE OFICINA;

USE OFICINA;

CREATE TABLE CLIENTE (
	IDCLIENTE INT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('F','M') NOT NULL
);

CREATE TABLE TELEFONE (
	IDTELEFONE INT,
	TIPO ENUM ('RES','CEL') NOT NULL,
	NUMERO VARCHAR(20) NOT NULL,
	ID_CLIENTE INT NOT NULL
);

CREATE TABLE CARRO (
	IDCARRO INT,
	MODELO VARCHAR(30) NOT NULL,
	PLACA CHAR(7) NOT NULL,
	ID_CLIENTE INT NOT NULL,
	ID_COR INT,
	ID_MARCA INT
);

CREATE TABLE COR (
	IDCOR INT,
	NOME VARCHAR(30) NOT NULL,
	VALOR FLOAT (6,2) NOT NULL,
	ID_CARRO INT NOT NULL
);

CREATE TABLE MARCA ( 
	IDMARCA INT,
	NOME VARCHAR(30) NOT NULL,
	VALOR_EXTRA FLOAT(6,2) NOT NULL,  /* VALOR EXTRA NO SERVIÇO PARA DETERMINADA MARCA*/
	ID_CARRO INT NOT NULL
);

CREATE TABLE SERVICO (
	IDSERVICO INT,
	NOME VARCHAR(30) NOT NULL,
	VALOR FLOAT (6,2) NOT NULL 
);

CREATE TABLE ATENDIMENTO(
	IDATENDIMENTO INT,
	ID_CARRO INT,
	ID_CLIENTE INT,
	DATA_ATD DATE NOT NULL,
	DESCRICAO VARCHAR(100)
);

CREATE TABLE ASS_CARRO_COR (
	IDCARRO INT, 
	IDCOR INT
);

CREATE TABLE ASS_SERVICO_ATENDIMENTO (
	IDSERVICO INT,
	IDATENDIMENTO INT
);



/* ---------------- CONSTRAINTS ------------------ */

/* CONSTRAINTS CLIENTE */
ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (IDCLIENTE);

ALTER TABLE CLIENTE MODIFY IDCLIENTE INT AUTO_INCREMENT;

/* CONSTRAINTS TELEFONE */

ALTER TABLE TELEFONE ADD CONSTRAINT PK_TELEFONE PRIMARY KEY (IDTELEFONE);

ALTER TABLE TELEFONE ADD CONSTRAINT FK_CLIENTE_TELEFONE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE);


/* CONSTRAINTS COR */

ALTER TABLE COR ADD CONSTRAINT PK_COR PRIMARY KEY (IDCOR);

ALTER TABLE COR MODIFY IDCOR INT AUTO_INCREMENT;

ALTER TABLE COR ADD CONSTRAINT UNQ_NOME_COR UNIQUE (NOME);

/* CONSTRAINTS MARCA */

ALTER TABLE MARCA ADD CONSTRAINT PK_MARCA
PRIMARY KEY (IDMARCA);

ALTER TABLE MARCA MODIFY IDMARCA INT AUTO_INCREMENT;

ALTER TABLE MARCA ADD CONSTRAINT UNQ_NOME_MARCA UNIQUE (NOME);

/* CONSTRAINTS SERVICO*/

ALTER TABLE SERVICO ADD CONSTRAINT PK_SERVICO
PRIMARY KEY (IDSERVICO);

ALTER TABLE SERVICO MODIFY IDSERVICO INT AUTO_INCREMENT;

ALTER TABLE SERVICO ADD CONSTRAINT UNQ_NOME_SERVICO
UNIQUE (NOME);

/* CONSTRAINTS CARRO */

ALTER TABLE CARRO ADD CONSTRAINT PK_CARRO PRIMARY KEY (IDCARRO);

ALTER TABLE CARRO MODIFY IDCARRO INT AUTO_INCREMENT;

ALTER TABLE CARRO ADD CONSTRAINT FK_CLIENTE_CARRO FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE);

ALTER TABLE CARRO ADD CONSTRAINT FK_COR_CARRO FOREIGN KEY (ID_COR) REFERENCES COR(IDCOR);

ALTER TABLE CARRO ADD CONSTRAINT FK_MARCA_CARRO FOREIGN KEY (ID_MARCA) REFERENCES MARCA(IDMARCA);

ALTER TABLE CARRO ADD CONSTRAINT UNQ_PLACA_CARRO UNIQUE (PLACA);

ALTER TABLE CARRO ADD CONSTRAINT UNQ_FK_CLIENTE_CARRO UNIQUE (ID_CLIENTE);  /* GARANTIR APENAS UM CARRO POR CLIENTE ( REGRA DE NEGÓCIO PARA EXERCÍCIO ) */

/* CONSTRAINTS ATENDIMENTO */

ALTER TABLE ATENDIMENTO ADD CONSTRAINT PK_ATENDIMENTO
PRIMARY KEY (IDATENDIMENTO );

ALTER TABLE ATENDIMENTO MODIFY IDATENDIMENTO INT AUTO_INCREMENT;

ALTER TABLE ATENDIMENTO ADD CONSTRAINT FK_CLIENTE_ATENDIMENTO
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE);

ALTER TABLE ATENDIMENTO ADD CONSTRAINT FK_CARRO_ATENDIMENTO
FOREIGN KEY (ID_CARRO) REFERENCES CARRO(IDCARRO);

/* CONSTRAINTS ASS_CARRO_COR */

ALTER TABLE ASS_CARRO_COR ADD CONSTRAINT PK_ASS_CARRO_COR
PRIMARY KEY (IDCARRO, IDCOR);

ALTER TABLE ASS_CARRO_COR ADD CONSTRAINT FK_COR_ASS_CARRO_COR
FOREIGN KEY (IDCOR) REFERENCES COR(IDCOR);

ALTER TABLE ASS_CARRO_COR ADD CONSTRAINT FK_CARRO_ASS_CARRO_COR
FOREIGN KEY (IDCARRO) REFERENCES CARRO(IDCARRO);

/* CONSTRAINTS ASS_SERVICO_ATENDIMENTO */

ALTER TABLE ASS_SERVICO_ATENDIMENTO ADD CONSTRAINT PK_ASS_SERVICO_ATENDIMENTO
PRIMARY KEY (IDATENDIMENTO);

ALTER TABLE ASS_SERVICO_ATENDIMENTO ADD CONSTRAINT FK_ATENDIMENTO_ASS_SERVICO_ATENDIMENTO
FOREIGN KEY (IDSERVICO) REFERENCES SERVICO(IDSERVICO);

ALTER TABLE ASS_SERVICO_ATENDIMENTO ADD CONSTRAINT FK_SERVICO_ASS_SERVICO_ATENDIMENTO
FOREIGN KEY (IDATENDIMENTO) REFERENCES ATENDIMENTO(IDATENDIMENTO);

/* VISUALIZAR CONSTRAINTS */
USE INFORMATION_SCHEMA;
SELECT CONSTRAINT_NAME, TABLE_SCHEMA, TABLE_NAME, CONSTRAINT_TYPE FROM TABLE_CONSTRAINTS WHERE CONSTRAINT_SCHEMA = 'OFICINA';

